##首页配置
server:
  tomcat:
    remote-ip-header: 127.0.0.1
    active: dev, prod

#  port: 8080
#  servlet:
#    context-path: /index

#数据库配置
spring:
  datasource:
    name: sherry  #数据库名
    url: jdbc:mysql://20sherry.com:20036/20sherry  #url
    username: root #用户名
    password: xl19980404mysql  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库链接驱动

  #thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML

    #    Email
  mail:
  # 配置 SMTP 服务器地址
  host: smtp.qq.com
  # 发送者邮箱
  username: 45257209@qq.com
  # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
  password: icvzelcejnjibjfj
  # 端口号465或587
  port: 587
  # 默认的邮件编码为UTF-8
  default-encoding: UTF-8
  # 配置SSL 加密工厂
  properties:
    mail:
      smtp:
        socketFactoryClass: javax.net.ssl.SSLSocketFactory
      #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
      debug: true

#   Swagger
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api-docs
        host: 20sherry.com:13142    #配置调用地址

#日志配置(无效)
logging:
  path: src/main/resources/ #日志文件路径
  file: ims.log #日志文件名称

#  config: classpath:logback-spring-bak.xml

